rika_sylius_brand_admin_brand:
    resource: |
        alias: rika_sylius_brand.brand
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: rika_sylius_brand_admin_brand
        vars:
            all:
                subheader: rika_sylius_brand.ui.manage_brands
            index:
                icon: 'trademark'
    type: sylius.resource