rika_sylius_brand_admin_brand:
    resource: |
        alias: rika_sylius_brand.brand
        section: admin
        templates: "@SyliusAdmin\\Crud"
        permission: true
        vars:
            all:
                subheader: rika_sylius_brand.ui.manage_brands
            index:
                icon: 'star'
    type: sylius.resource
