rika_brand_admin_index:
    path: /brands
    methods: [GET]
    defaults:
        _controller: rika.controller.brand::indexAction
        _sylius:
            template: "@RikaSyliusBrandPlugin/Admin/Brand/index.html.twig"

rika_brand_admin_create:
    path: /brands/new
    methods: [GET, POST]
    defaults:
        _controller: rika.controller.brand::createAction
        _sylius:
            template: "@RikaSyliusBrandPlugin/Admin/Brand/create.html.twig"
            redirect: rika_brand_admin_show

rika_brand_admin_update:
    path: /brands/{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: rika.controller.brand::updateAction
        _sylius:
            template: "@RikaSyliusBrandPlugin/Admin/Brand/update.html.twig"
            redirect: rika_brand_admin_show

rika_brand_admin_show:
    path: /brands/{id}
    methods: [GET]
    defaults:
        _controller: rika.controller.brand::showAction
        _sylius:
            template: "@RikaSyliusBrandPlugin/Admin/Brand/show.html.twig"

rika_brand_admin_delete:
    path: /brands/{id}
    methods: [DELETE]
    defaults:
        _controller: rika.controller.brand::deleteAction
        _sylius:
            redirect: rika_brand_admin_index
