admin_brand:
    resource: |
        alias: rika_sylius_brand.brand
        section: admin
        templates: "@SyliusAdmin/shared/crud"
        redirect: update
        grid: admin_brand
        vars:
            all:
                subheader: rika_sylius_brand.ui.brands
            index:
                icon: 'star'
    type: sylius.resource