rika_brand_admin:
    resource: |
        alias: rika.brand
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: rika_brand_admin
        vars:
            all:
                subheader: rika.ui.manage_brands
            index:
                icon: 'trademark'
    type: sylius.resource
