rika_sylius_brand_admin_brand:
    resource: |
        alias: rika_sylius_brand.brand
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: rika_sylius_brand_admin_brand
        vars:
            all:
                subheader: rika_sylius_brand.ui.brands
                templates:
                    form: "@RikaSyliusBrandPlugin/Admin/Brand/_form.html.twig"
            index:
                icon: 'tag icon'
    type: sylius.resource