sylius_grid:
    grids:
        rika_sylius_brand_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: Rika\SyliusBrandPlugin\Entity\Brand
            fields:
                name:
                    type: string
                    label: rika_sylius_brand_plugin.ui.name
                    sortable: ~
                logo:
                    type: twig
                    label: rika_sylius_brand_plugin.ui.logo
                    options:
                        template: "@RikaSyliusBrandPlugin/Admin/Brand/Grid/Field/logo.html.twig"
                description:
                    type: string
                    label: rika_sylius_brand_plugin.ui.description
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
