sylius_grid:
    grids:
        admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: Rika\SyliusBrandPlugin\Entity\Brand
                    repository:
                        method: createListQueryBuilder
                        arguments: ['%sylius.admin_user.locale%']
            sorting:
                position: asc
            fields:
                logo:
                    type: twig
                    label: sylius.ui.logo
                    options:
                        template: "@RikaSyliusBrandPlugin/Admin/Brand/Grid/Field/logo.html.twig"
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: twig
                    label: sylius.ui.name
                    options:
                        template: "@SyliusUi/Grid/Field/string.html.twig"
                        vars:
                            data: resource.name
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                position:
                    type: string
                    label: sylius.ui.position
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [translations.name]
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
                        label: sylius.ui.create
                item:
                    update:
                        type: update
                        label: sylius.ui.edit
                    delete:
                        type: delete
                        label: sylius.ui.delete