sylius_grid:
    grids:
        rika_sylius_brand_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: Rika\SyliusBrandPlugin\Entity\Brand
                    repository:
                        method: createListQueryBuilder
            sorting:
                position: asc
            fields:
                logo:
                    type: twig
                    label: rika_sylius_brand.ui.logo
                    sortable: false
                    options:
                        template: '@RikaSyliusBrandPlugin/Admin/Brand/Grid/Field/logo.html.twig'
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
                    path: translation.name
                slug:
                    type: string
                    label: sylius.ui.slug
                    sortable: translation.slug
                    path: translation.slug
                position:
                    type: string
                    label: sylius.ui.position
                    sortable: position
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: enabled
                    options:
                        template: '@SyliusUi/Grid/Field/enabled.html.twig'
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [translation.name, translation.slug]
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    show:
                        type: show
                    update:
                        type: update
                    delete:
                        type: delete