services:
    # Configuration explicite (supprimez la section _defaults problématique)
    
    # Menu Listener - Configuration explicite
    Rika\SyliusBrandPlugin\Menu\AdminMenuListener:
        arguments: []
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: __invoke }

    # Repository personnalisé
    Rika\SyliusBrandPlugin\Repository\BrandRepository:
        class: Rika\SyliusBrandPlugin\Repository\BrandRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - !service
                class: Doctrine\ORM\Mapping\ClassMetadata
                factory: ['@doctrine.orm.entity_manager', getClassMetadata]
                arguments:
                    - 'Rika\SyliusBrandPlugin\Entity\Brand'
            - '@sylius.context.locale'
        tags:
            - { name: 'doctrine.repository_service' }

    # Alias pour que Sylius trouve le repository
    rika_sylius_brand.repository.brand: '@Rika\SyliusBrandPlugin\Repository\BrandRepository'

    # Factory avec initialisation de locale
    Rika\SyliusBrandPlugin\Factory\BrandFactory:
        autowire: false
        arguments:
            - !service
                class: Sylius\Resource\Factory\Factory
                arguments:
                    - 'Rika\SyliusBrandPlugin\Entity\Brand'
            - '@sylius.context.locale'

    # Alias pour que Sylius trouve la factory
    rika_sylius_brand.factory.brand: '@Rika\SyliusBrandPlugin\Factory\BrandFactory'

    rika_sylius_brand.factory.brand_translation:
        class: Sylius\Resource\Factory\Factory
        arguments:
            - 'Rika\SyliusBrandPlugin\Entity\BrandTranslation'

    # Event subscribers / listeners
    Rika\SyliusBrandPlugin\EventListener\BrandEventListener:
        arguments:
            $uploadDir: '%rika_sylius_brand.upload_dir%'
        tags:
            - { name: kernel.event_subscriber }

    Rika\SyliusBrandPlugin\EventListener\BrandSlugListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Rika\SyliusBrandPlugin\EventListener\ProductMappingListener:
        tags:
            - { name: doctrine.event_subscriber, priority: 100 }

    # Form types
    Rika\SyliusBrandPlugin\Form\Type\BrandType:
        arguments:
            $dataClass: 'Rika\SyliusBrandPlugin\Entity\Brand'
            $validationGroups: ['sylius']
        tags:
            - { name: 'form.type' }

    Rika\SyliusBrandPlugin\Form\Type\BrandTranslationType:
        arguments:
            $dataClass: 'Rika\SyliusBrandPlugin\Entity\BrandTranslation'
            $validationGroups: ['sylius']
        tags:
            - { name: 'form.type' }

    Rika\SyliusBrandPlugin\Form\Type\BrandChoiceType:
        tags:
            - { name: 'form.type' }

    # Form extensions
    Rika\SyliusBrandPlugin\Form\Extension\ProductTypeExtension:
        tags:
            - { name: 'form.type_extension', extended_type: 'Sylius\Bundle\ProductBundle\Form\Type\ProductType' }