sylius_grid:
    grids:
        admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: Rika\SyliusBrandPlugin\Entity\Brand
            sorting:
                name: asc
            fields:
                logo:
                    type: twig
                    label: rika_sylius_brand.ui.logo
                    options:
                        template: "@RikaSyliusBrandPlugin/Admin/Brand/Grid/Field/logo.html.twig"
                name:
                    type: string
                    label: rika_sylius_brand.form.brand.name
                slug:
                    type: string
                    label: rika_sylius_brand.form.brand.slug
                position:
                    type: string
                    label: rika_sylius_brand.ui.position
                enabled:
                    type: twig
                    label: rika_sylius_brand.form.brand.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [translation.name, translation.slug]
                enabled:
                    type: boolean
                    label: rika_sylius_brand.form.brand.enabled
            actions:
                main:
                    create:
                        type: create
                        label: rika_sylius_brand.ui.new_brand
                item:
                    update:
                        type: update
                        label: sylius.ui.edit
                    delete:
                        type: delete
                        label: sylius.ui.delete
