# src/Resources/config/sylius_resource.yaml
sylius_resource:
    resources:
        rika_sylius_brand_plugin.brand:
            driver: doctrine/orm
            classes:
                model: Rika\SyliusBrandPlugin\Entity\Brand
                repository: Rika\SyliusBrandPlugin\Repository\BrandRepository
                form: Rika\SyliusBrandPlugin\Form\Type\BrandType
                interface: Rika\SyliusBrandPlugin\Entity\BrandInterface
            validation_groups:
                default: [rika_sylius_brand]
        rika_sylius_brand_plugin.brand_translation:
            driver: doctrine/orm
            classes:
                model: Rika\SyliusBrandPlugin\Entity\BrandTranslation
                form: Rika\SyliusBrandPlugin\Form\Type\BrandTranslationType
                interface: Rika\SyliusBrandPlugin\Entity\BrandTranslationInterface
