sylius_resource:
    resources:
        rika_sylius_brand_plugin.brand:
            driver: doctrine/orm
            classes:
                model: Rika\SyliusBrandPlugin\Entity\Brand
                interface: Rika\SyliusBrandPlugin\Entity\BrandInterface
                repository: Rika\SyliusBrandPlugin\Repository\BrandRepository
                form: Rika\SyliusBrandPlugin\Form\Type\BrandType
            templates: "@RikaSyliusBrandPlugin/Admin/Brand"
