sylius_resource:
    resources:
        rika.brand:
            driver: doctrine/orm
            classes:
                model: Rika\SyliusBrandPlugin\Entity\Brand
                form: Rika\SyliusBrandPlugin\Form\Type\BrandType
                interface: Rika\SyliusBrandPlugin\Entity\BrandInterface
            translation:
                classes:
                    model: Rika\SyliusBrandPlugin\Entity\BrandTranslation
                    interface: Rika\SyliusBrandPlugin\Entity\BrandTranslationInterface
