sylius_resource:
    resources:
        rika_sylius_brand.brand:
            driver: doctrine/orm
            classes:
                model: Rika\SyliusBrandPlugin\Entity\Brand
                interface: Rika\SyliusBrandPlugin\Entity\BrandInterface
                repository: Rika\SyliusBrandPlugin\Repository\BrandRepository
                form: Rika\SyliusBrandPlugin\Form\Type\BrandType
            translation:
                classes:
                    model: Rika\SyliusBrandPlugin\Entity\BrandTranslation
                    interface: Rika\SyliusBrandPlugin\Entity\BrandTranslationInterface
                    form: Rika\SyliusBrandPlugin\Form\Type\BrandTranslationType