imports:
    - { resource: "@RikaSyliusBrandPlugin/config/services.yaml" }
    - { resource: "@RikaSyliusBrandPlugin/config/routes.yaml" }
    - { resource: "@RikaSyliusBrandPlugin/config/twig_hooks/**/*.yaml" }
    - { resource: "@RikaSyliusBrandPlugin/config/grids/**/*.yaml" }

parameters:
    rika_sylius_brand.upload_dir: "%kernel.project_dir%/public/media/brands"