# Configuration du plugin Brand - définition minimale nécessaire

# Définition par défaut des ressources (utilisée par l'Extension)
rika_sylius_brand:
    resources:
        brand:
            classes:
                model: Rika\SyliusBrandPlugin\Entity\Brand
                repository: Rika\SyliusBrandPlugin\Repository\BrandRepository
                factory: Rika\SyliusBrandPlugin\Factory\BrandFactory
                form: Rika\SyliusBrandPlugin\Form\Type\BrandType
            translation:
                classes:
                    model: Rika\SyliusBrandPlugin\Entity\BrandTranslation
                    form: Rika\SyliusBrandPlugin\Form\Type\BrandTranslationType

# Configuration pour l'application utilisateur
sylius_grid:
    grids:
        rika_sylius_brand_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: Rika\SyliusBrandPlugin\Entity\Brand
            sorting:
                position: asc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
                    path: translation.name
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: enabled
                    options:
                        template: '@SyliusUi/Grid/Field/enabled.html.twig'
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

# Imports des hooks Twig
imports:
    - { resource: "twig_hooks/**/*.yaml" }