imports:
    - { resource: "@RikaSyliusBrandPlugin/config/grids/admin/admin.yaml" }
    - { resource: "@RikaSyliusBrandPlugin/config/routes/admin.yaml" }
    - { resource: "@RikaSyliusBrandPlugin/config/twig_hooks/admin/admin.yaml" }
    - { resource: "@RikaSyliusBrandPlugin/config/twig_hooks/shop/shop.yaml" }

parameters:
    rika_sylius_brand.upload_dir: "%kernel.project_dir%/public/media/brands"