imports:
    - { resource: "@RikaSyliusBrandPlugin/config/routes/*.yaml" }

rika_sylius_brand_admin:
    resource: "@RikaSyliusBrandPlugin/config/routes/admin.yaml"
    prefix: '/%sylius_admin.path_name%'