imports:
    - { resource: 'services/' }

parameters:
    rika_sylius_brand.model.brand.class: 'Rika\SyliusBrandPlugin\Entity\Brand'
    rika_sylius_brand.model.brand_translation.class: 'Rika\SyliusBrandPlugin\Entity\BrandTranslation'
    rika_sylius_brand.upload_dir: '%kernel.project_dir%/public/media/brands'

services:
    _defaults:
        public: true

    # Repository personnalisé
    Rika\SyliusBrandPlugin\Repository\BrandRepository:
        autowire: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - !service
                class: 'Doctrine\ORM\Mapping\ClassMetadata'
                factory: ['@doctrine.orm.entity_manager', 'getClassMetadata']
                arguments:
                    - '%rika_sylius_brand.model.brand.class%'
            - '@sylius.context.locale'
        tags:
            - { name: doctrine.repository_service }

    # Alias pour le repository
    rika_sylius_brand.repository.brand: '@Rika\SyliusBrandPlugin\Repository\BrandRepository'

    # Factory Brand
    Rika\SyliusBrandPlugin\Factory\BrandFactory:
        autowire: false
        arguments:
            - !service
                class: 'Sylius\Resource\Factory\Factory'
                arguments:
                    - '%rika_sylius_brand.model.brand.class%'
            - '@sylius.context.locale'

    # Alias pour la factory Brand
    rika_sylius_brand.factory.brand: '@Rika\SyliusBrandPlugin\Factory\BrandFactory'

    # Factory Brand Translation
    rika_sylius_brand.factory.brand_translation:
        class: 'Sylius\Resource\Factory\Factory'
        arguments:
            - '%rika_sylius_brand.model.brand_translation.class%'

    # Event Listeners
    Rika\SyliusBrandPlugin\EventListener\BrandEventListener:
        autowire: true
        autoconfigure: true
        arguments:
            $uploadDir: '%rika_sylius_brand.upload_dir%'
        tags:
            - { name: kernel.event_subscriber }

    Rika\SyliusBrandPlugin\EventListener\BrandSlugListener:
        autowire: true
        autoconfigure: true
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Rika\SyliusBrandPlugin\EventListener\ProductMappingListener:
        autowire: true
        autoconfigure: true
        tags:
            - { name: doctrine.event_subscriber, priority: 100 }

    # Form Types
    Rika\SyliusBrandPlugin\Form\Type\BrandType:
        autowire: false
        arguments:
            $dataClass: '%rika_sylius_brand.model.brand.class%'
            $validationGroups: ['sylius']
        tags:
            - { name: form.type }

    Rika\SyliusBrandPlugin\Form\Type\BrandTranslationType:
        autowire: false
        arguments:
            $dataClass: '%rika_sylius_brand.model.brand_translation.class%'
            $validationGroups: ['sylius']
        tags:
            - { name: form.type }

    Rika\SyliusBrandPlugin\Form\Type\BrandChoiceType:
        autowire: true
        autoconfigure: true
        tags:
            - { name: form.type }

    # Form Extension
    Rika\SyliusBrandPlugin\Form\Extension\ProductTypeExtension:
        autowire: true
        autoconfigure: true
        tags:
            - { name: form.type_extension, extended_type: 'Sylius\Bundle\ProductBundle\Form\Type\ProductType' }