sylius_grid:
    grids:
        rika_sylius_brand_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: "Rika\\SyliusBrandPlugin\\Entity\\Brand"
            sorting:
                position: asc
            fields:
                name:
                    type: twig
                    label: sylius.ui.name
                    sortable: translation.name
                    options:
                        template: "@SyliusAdmin/shared/grid/field/translatable_string.html.twig"
                slug:
                    type: twig
                    label: sylius.ui.slug
                    sortable: translation.slug
                    options:
                        template: "@SyliusAdmin/shared/grid/field/translatable_string.html.twig"
                position:
                    type: string
                    label: sylius.ui.position
                    sortable: position
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: enabled
                    options:
                        template: "@SyliusAdmin/shared/grid/field/enabled.html.twig"
            actions:
                item:
                    show:
                        type: show
                        label: sylius.ui.show
                        icon: "tabler:eye"
                    update:
                        type: update
                        label: sylius.ui.edit
                        icon: "tabler:pencil"
                    delete:
                        type: delete
                        label: sylius.ui.delete
                        icon: "tabler:trash"
                main:
                    create:
                        type: create
                        label: sylius.ui.create
                        icon: "tabler:plus"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                enabled:
                    type: boolean
                    label: sylius.ui.enabled