rika_sylius_brand_admin_brand:
    resource: |
        alias: rika_sylius_brand.brand
        section: admin
        templates: "@SyliusAdmin/shared/crud"
        redirect: update
        grid: rika_sylius_brand_admin_brand
        permission: true
        vars:
            all:
                subheader: rika_sylius_brand.ui.manage_brands
                header: rika_sylius_brand.ui.brands
            index:
                icon: 'star'
    type: sylius.resource
