rika_sylius_brand_shop_brand:
    resource: |
        alias: rika_sylius_brand.brand
        section: shop
        templates: "@RikaSyliusBrandPlugin/Shop/Brand"
        only: ['index', 'show']
    type: sylius.resource
